# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXFN2UaTDUC1rt--jqr9OTgkm7XLHmx5
"""

app_py = """
from flask import Flask, request, render_template_string
import joblib
import re

app = Flask(__name__)

def clean_text(text):
    text = re.sub(r"http\\S+", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    return text.lower()

@app.route("/", methods=["GET", "POST"])
def index():
    result = None
    if request.method == "POST":
        text = request.form["text"]
        cleaned = clean_text(text)
        # prediction = model.predict([cleaned])[0]
        prediction = "誹謗中傷の可能性あり" if "死ね" in cleaned else "安全な発言"
        result = f"判定結果：{prediction}"
    return render_template_string(\"""
        <h1>🐋 クジラボットへようこそ</h1>
        <form method="post">
            <textarea name="text" rows="4" cols="50" placeholder="ここにツイート内容を入力してください..."></textarea><br>
            <input type="submit" value="判定する">
        </form>
        {% if result %}
        <p><strong>{{ result }}</strong></p>
        {% endif %}
    \""", result=result)

if __name__ == "__main__":
    app.run(debug=True)
"""

with open("app.py", "w") as f:
    f.write(app_py)

requirements_txt = """
Flask
gunicorn
joblib
"""

with open("requirements.txt", "w") as f:
    f.write(requirements_txt)

render_yaml = """
services:
  - type: web
    name: whaleheart-service
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    autoDeploy: true
"""

with open(".render.yaml", "w") as f:
    f.write(render_yaml)

