# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVh6RetJc-PLsg4tpa2h8COhukBUQH2b
"""

with open('requirements.txt', 'w') as f:
    f.write('''flask
transformers
torch
pandas
numpy
scikit-learn
''')

